### ISSUE TITLE
[ 혜수 ] 사이드바 반응형 추가  

### ISSUE THREAD

**Issue by suehdn** [prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan#147]
## 📝 TODO
- 사이드바 반응형 추가  
## 🚀 구현 계획
- [x] 브라우저가 일정 크기 이상 줄어들면 사이드바가 보이지 않게 수정 (왼쪽으로 사라지는 모션이 좋을것 같음)
- [x] 브라우저가 사라졌을 때 다시 보이게하는 버튼 추가하기
- [x] 버튼 누르면 사이드바가 다시 나타나기 (오른쪽으로 나오는 모션)
## 📘 참고 사항
- React Transition Group 도입
