### ISSUE TITLE
[ 김동현 ] api url 상수화 시키기, (API 파라미터, 데이터) 타입 정의하기

### ISSUE THREAD

**Issue by doggopawer** [prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan#19]
## 📝 TODO
api url을 상수화 시킵니다.
## 🚀 구현 계획
- [x] API_URL로 객체를 만든다.
- [x] 세부 도메인에 해당하는 속성을 각각 만들어준다. 
- [x] 필요한 타입을 정의한다.
