### ISSUE TITLE
[ 혜수 ]  아이콘 + 텍스트 molecule 제작

### ISSUE THREAD

**Issue by suehdn** [prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan#22]
## 📝 TODO
- [x] 아이콘 + 텍스트 molecule 만들기 
## 🚀 구현 계획
- [x] 아이콘 atom 이용
- [x] 텍스트 atom 이용
