### ISSUE TITLE
[ 혜수 ] (임시) font & Reset global 설정 

### ISSUE THREAD

**Issue by suehdn** [prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan#23]
## 📝 TODO
- [x] 전역 폰트 설정
- [x] CSS Reset 설정
## 🚀 구현 계획
- [x] IBM Plex Sans KR로 임시 지정
- [x] emotion을 이용해 global 지정
