### ISSUE TITLE
[ 혜수 ] FloatingButton molecule 제작

### ISSUE THREAD

**Issue by suehdn** [prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan#30]
## 📝 TODO
- [x] FloatingButton molecule 제작
## 🚀 구현 계획
- [x] 아이콘 atom 이용
- [x] 버튼 atom 이용
