### ISSUE TITLE
[ 혜수 ] 사용할 수 있는 svg파일 추가

### ISSUE THREAD

**Issue by suehdn** [prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan#32]
## 📝 TODO
- [x] svg 파일 추가 
## 🚀 구현 계획
- [x] alert, folder, home, like, message, my, question, search, upperBracket 파일 추가
- [x] width, height, fill -> "current"로 변경
