### ISSUE TITLE
[ 혜수 ] 사이드바 Organism 제작 

### ISSUE THREAD

**Issue by suehdn** [prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan#38]
## 📝 TODO
- 사이드바 제작하기
- 숨김 기능이 있어야함 ( 단, 전체 화면에선 숨김기능 없고 일정 width 미만일 때 숨김, 나타내기 버튼 활성화)
## 🚀 구현 계획
- [x] 아이콘 + 텍스트 molecule 이용
- [x] 로그아웃 버튼
- [x] 다크모드/ 라이트모드 토글
- [x] sticky or fix 기능

## 📘 참고 사항
ArticleEditor에 주석이 많은데 사용할 수 도 있는 부분이라 일단 주석처리했습니다.
