### ISSUE TITLE
[ 안혜수 ]  atom 제작 - 텍스트

### ISSUE THREAD

**Issue by suehdn** [prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan#5]
## 📝 TODO
- [ ] atoms 폴더에 텍스트 컴포넌트 제작하기

## 🚀 구현 계획
- [ ] 텍스트가 필요한 모든 molecule, organism에서 사용할 수 있도록 제작
- [ ] Storybook에서 볼 수 있도록 제작
