### ISSUE TITLE
[ 혜수 ]  사이드바 채널 생성시 채널 동적으로 변경 되도록 수정, 디자인 수정

### ISSUE THREAD

**Issue by suehdn** [prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan#73]
## 📝 TODO
- 사이드바 채널 생성시 채널 동적으로 변경 되도록 수정
-> 현재 일일히 추가해야 하는 방식으로 구현되어있음 
- 디자인 수정 (급하게 생성해서 디자인 이상함)
## 🚀 구현 계획
- [x] 사이드바 글씨 크기 수정 -> 14px 정도
- [x] 사이드바 hover시 마우스 포인터 변경
- [x] main, channels 헤더 추가
- [x] 채널 동적 변경!
