### ISSUE TITLE
[ 혜수 ] 글 작성 페이지 API 연결 

### ISSUE THREAD

**Issue by suehdn** [prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan#75]
## 📝 TODO
- 글 작성 페이지 API 연결하기
## 🚀 구현 계획
- [ ] useChannelsQuery hook을 이용해 채널 정보 받아오기
- [ ] 글쓰기 페이지에서 채널 선택하면 channelId 변경하기
- [ ] title: String 아래와 같은 방식으로 데이터 넣기
```
  title: string;
  content: string;
  tags: string[];
``` 

## 📘 참고 사항
```
title: String,
image: Binary | null,
channelId: String
```
