### ISSUE TITLE
[ 혜수 ] 새 글 작성 버튼 & 맨 위로가기 버튼 추가 

### ISSUE THREAD

**Issue by suehdn** [prgrms-fe-devcourse/FEDC4_SCRAWL_Yohan#95]
## 📝 TODO
- 새 글 작성 버튼 & 맨 위로가기 버튼 추가 
## 🚀 구현 계획
- [x] organisms/FloatingButtons 폴더 추가
- [ ] 로그인이 되었을 때만 보이도록 만들기
- [ ] 새 글 작성 버튼 클릭시 새 글 작성 페이지로 이동
- [ ] 맨 위로가기 버튼 클릭시 페이지의 맨 위로 이동
